In [1]:
import numpy as np

# Multidimensional Arraylerin Elemanlarına Ulaşmak 

In [3]:
a = np.arange(1,21).reshape(4,5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
a[0]

array([1, 2, 3, 4, 5])

In [6]:
a[1]

array([ 6,  7,  8,  9, 10])

In [7]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
a[0,0]

1

In [9]:
a[0][0]

1

In [10]:
a[1,1]

7

In [11]:
a[0,1]

2

In [12]:
a.ndim

2

In [13]:
a[0].ndim

1

In [14]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
a[1,1] = 20.40

In [16]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
a[1,1] = "30"

In [18]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[1,1] = "30.5"

ValueError: invalid literal for int() with base 10: '30.5'

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Slice Index

In [21]:
a = np.arange(1,21).reshape(4,5)

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
a[1]

array([ 6,  7,  8,  9, 10])

In [24]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
a[:1]

array([[1, 2, 3, 4, 5]])

In [29]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [32]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [35]:
a[:,3]

array([ 4,  9, 14, 19])

In [34]:
a[::2,3]

array([ 4, 14])

In [36]:
a[0,:]

array([1, 2, 3, 4, 5])

In [37]:
a[0]

array([1, 2, 3, 4, 5])

In [38]:
a[0,2:4]

array([3, 4])

In [39]:
a[0:2,0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [40]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [42]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

#  Fancy Index

In [43]:
import numpy as np

In [44]:
x = np.arange(1,15)

In [45]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
idxs = [4,5,7,11]

In [47]:
x[idxs]

array([ 5,  6,  8, 12])

In [48]:
a = np.arange(12).reshape(3,4)

In [49]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a[0:2,1]

array([1, 5])

In [51]:
a[0:2,1].shape

(2,)

In [52]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [53]:
a[0:2,1:3].shape

(2, 2)

In [54]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a[0,[1,3]]

array([1, 3])

In [56]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [57]:
a = np.arange(20).reshape(4,5)

In [58]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
idxs1 = [1,3,2]

In [60]:
idxs2 = [3,0,2]

In [61]:
a[idxs1, idxs2]

array([ 8, 15, 12])

In [62]:
a[idxs1][idxs2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [63]:
x[[1,2,3]] = 20

In [64]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
x = np.arange(9)

In [66]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
x[[1,2,3]] = [100,200,300]

In [68]:
x

array([  0, 100, 200, 300,   4,   5,   6,   7,   8])

In [69]:
t = (1,2,3,4,5,6)

In [70]:
t

(1, 2, 3, 4, 5, 6)

In [71]:
t[0]

1

In [72]:
t[0].ndim

AttributeError: 'int' object has no attribute 'ndim'

In [73]:
t[0].shape

AttributeError: 'int' object has no attribute 'shape'

In [74]:
t[0].size

AttributeError: 'int' object has no attribute 'size'