In [1]:
import numpy as np

# All

Tüm elemanlar verilen şartı sağlıyor mu kontrol etmek

In [2]:
a = np.arange(20).reshape(4,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a >- 1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [5]:
np.all(a>-1)

True

In [6]:
filt = a >- 1

In [7]:
np.all(filt)

True

In [8]:
np.all(a>-1, axis=0)

array([ True,  True,  True,  True,  True])

In [9]:
np.all(a>-1, axis=1)

array([ True,  True,  True,  True])

In [10]:
a > 4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
np.all(a>4)

False