In [12]:
import numpy as np

In [13]:
#SUBARRAY
a = np.arange(1,21).reshape(4,5)

In [14]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
b = a[:2,:3]

In [16]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [17]:
b.ndim

2

In [18]:
b[0,0] = 100

In [19]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [20]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [21]:
#COPY
a = np.arange(1,21).reshape(4,5)

In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
b = a[:2,:3].copy()

In [24]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [25]:
b[0,0] = 100

In [26]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [27]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])