In [1]:
import numpy as np

In [2]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
x.shape

(2, 3)

In [7]:
y.shape

(2, 5, 4)

In [8]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
x.ndim

2

In [11]:
y.ndim

3

In [12]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [14]:
x.size

6

In [15]:
y.size

40

In [16]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
x.dtype

dtype('float64')

In [19]:
y.dtype

dtype('float64')