In [1]:
import numpy as np

# Conditional Indexing

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]

array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
filt = a<3

In [8]:
a[filt]

array([1, 2])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [11]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [12]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [13]:
a[a==b]

array([3, 4, 5, 7, 8])

In [14]:
b[a==b]

array([3, 4, 5, 7, 8])

In [15]:
#Broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [16]:
a ==1

array([ True, False, False, False, False, False, False, False, False])

In [17]:
(a<3) or (a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [19]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [20]:
filt = (a<3) | (a>5)

In [21]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [22]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [24]:
a[(a>3) & (a<=5)]

array([4, 5])

# Filtrenin Değili

In [25]:
a = np.arange(1,21).reshape(4,5)

In [26]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
filt = a<5

In [28]:
a[filt]

array([1, 2, 3, 4])

In [29]:
filt = (a>5) & (a<9)

In [30]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [31]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [32]:
filt = ~((a>5) & (a<9))

In [33]:
filt

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [34]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])