In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np.array([5,6,7,8])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([5, 6, 7, 8])

In [6]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

Python listlerin de numpy arrayleri ile concat'a sokabiliriz

In [7]:
l = [10,11]

In [8]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [13]:
l = [10,11,11.2]

In [14]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [9]:
l = [10,11,"11.2"]

In [10]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U11')

Python tuple'larını da numpy arrayleri ile concat'a sokabiliriz

In [11]:
l = (10,11)

In [12]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

# Size Mismatch

In [15]:
a

array([1, 2, 3, 4])

In [16]:
x = np.array([[1,2,3],[4,5,6]])

In [17]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x.size

6

In [19]:
x.shape

(2, 3)

In [20]:
a.shape

(4,)

In [21]:
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [22]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [24]:
np.concatenate([x,x], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])