In [1]:
import numpy as np

# Normal Distribution'dan Çekilmiş Değerler ile Array Oluşturmak

(mean, std, array size)

In [2]:
np.random.normal(0,1,(4,5))

array([[-0.7749065 ,  0.26128191,  1.2429482 ,  1.25228492,  0.62213483],
       [ 1.2714816 , -0.43970419, -1.525862  , -0.01740691, -0.42657773],
       [ 0.23506995, -0.42949384,  0.39974605, -0.11674991,  0.26346343],
       [-0.97374074,  0.36384394,  0.97950329,  0.01478417, -0.46180488]])

In [3]:
np.random.normal(0,100,(4,5))

array([[  -0.45286295,  -22.86104634,  -63.06902748,   75.44845796,
          88.74388913],
       [  54.22906087,   49.16337346,  -89.20539654,  114.68585995,
          62.6359404 ],
       [ -37.77493566, -108.88085891,  165.60369845,  -93.494275  ,
          76.41558686],
       [ -46.21124182,  -57.37318062,   83.56758261,   57.46021425,
         153.44972093]])

In [4]:
np.random.normal(10,100,(4,5))

array([[-142.81251532,   43.07025623,   66.17107924,  -38.96244368,
          13.00752614],
       [ -75.06882658,  -60.70469148,  -38.88632043,  -76.03317244,
         247.33657135],
       [ 236.7151159 ,  -54.05705529,  -11.56596623,   37.52231949,
           0.83463931],
       [ -15.19637927,   54.53924596,  -48.82136373,  -16.61543027,
          65.88425472]])

In [5]:
np.random.normal(10,1,(4,5))

array([[10.25017581, 10.24600911, 10.0945243 , 10.74151302, 10.44813   ],
       [10.57767102,  9.79623264, 11.58196322,  9.82896982, 11.64285184],
       [11.39916317,  9.81559024, 10.77512471,  9.29989738,  9.9563832 ],
       [ 8.9354291 , 10.31558945,  8.53356864, 11.1533938 ,  9.94194766]])