In [1]:
import numpy as np

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
np.sum(a)

210

In [5]:
filt = a < 5

In [6]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [7]:
np.sum(filt)

4

In [8]:
a[filt]

array([1, 2, 3, 4])

In [9]:
np.sum(a[filt])

10

In [10]:
filt = (a > 5) & (a < 9)

In [11]:
np.sum(filt)

3

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
a[filt]

array([6, 7, 8])

In [14]:
np.sum(a[(a > 5) & (a < 9)])

21

In [15]:
filt = ~((a>5) & (a<9))

In [16]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
np.sum( ~((a>5) & (a<9)))

17

In [18]:
np.sum(a[~((a>5) & (a<9))])

189

# Belirli axis Üzerinde Toplama

In [19]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [20]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])